CREATE DATABASE ShopifyLite;

USE ShopifyLite;

CREATE TABLE `PRODUCTS`(
    `ID` INT(11) PRIMARY KEY AUTO_INCREMENT,
    `NAME` VARCHAR(255) NOT NULL,
    `PRICE` DECIMAL(10,2) NOT NULL
);

INSERT INTO `PRODUCTS` (NAME, PRICE) VALUES ("LAPTOP", 50000);
INSERT INTO `PRODUCTS` (NAME, PRICE) VALUES ("TABLET", 15000);
INSERT INTO `PRODUCTS` (NAME, PRICE) VALUES ("SMART PHONE", 25000);

SHOW TABLES;

CREATE TABLE `CUSTOMERS`(
    `ID` INT(11) PRIMARY KEY AUTO_INCREMENT,
    `NAME` VARCHAR(255) DEFAULT NULL,
    `ADDRESS` TEXT(100) NOT NULL
);

DESC `CUSTOMERS`;

INSERT INTO `CUSTOMERS` (NAME, ADDRESS) VALUES ("SANJANA", "MH");
INSERT INTO `CUSTOMERS` (NAME, ADDRESS) VALUES ("ANA", "RAJ");
INSERT INTO `CUSTOMERS` (NAME, ADDRESS) VALUES ("NAVEEN", "HR");
INSERT INTO `CUSTOMERS` (NAME, ADDRESS) VALUES ("DEEPA", "UP");
INSERT INTO `CUSTOMERS` (NAME, ADDRESS) VALUES ("YASH", "AP");
INSERT INTO `CUSTOMERS` (NAME, ADDRESS) VALUES ("JAY", "CH");
INSERT INTO `CUSTOMERS` (NAME, ADDRESS) VALUES ("MAHI", "GUJ");
INSERT INTO `CUSTOMERS` (NAME, ADDRESS) VALUES ("MEENAL", "MH");
INSERT INTO `CUSTOMERS` (NAME, ADDRESS) VALUES ("SWETA", "UPE");

#ADDING COLUMN
ALTER TABLE `CUSTOMERS` ADD COLUMN (`ADDRESS` TEXT(100) NOT NULL);

DESC `CUSTOMERS`;

#UPDATING COLUMN
ALTER TABLE `CUSTOMERS` MODIFY COLUMN NAME VARCHAR(70) NOT NULL;

#REMOVING COLUMN
ALTER TABLE `CUSTOMERS` DROP COLUMN `IDENTITY`;

#RENAME COLUMN 
ALTER TABLE `CUSTOMERS` RENAME COLUMN NAME TO NAMES;

CREATE TABLE `ORDERS`(
    `ID` INT(11) PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_ID INT(11) NOT NULL,
    ORDER_NUMBER VARCHAR(255) NOT NULL,
    ORDER_AT DATETIME NOT NULL
);

#ADDING FOREIGN KEY
ALTER TABLE `ORDERS` ADD FOREIGN KEY(CUSTOMER_ID) REFERENCES `CUSTOMERS`(ID);

DESC `ORDERS`;

INSERT INTO ORDERS (CUSTOMER_ID, ORDER_NUMBER, ORDER_AT) VALUES (1, 'ORD123', '2023-01-01 10:00:00');
INSERT INTO ORDERS (CUSTOMER_ID, ORDER_NUMBER, ORDER_AT) VALUES (4, 'ORD456', '2023-01-02 14:30:00');
INSERT INTO ORDERS (CUSTOMER_ID, ORDER_NUMBER, ORDER_AT) VALUES (3, 'ORD789', '2023-01-03 09:45:00');
INSERT INTO ORDERS (CUSTOMER_ID, ORDER_NUMBER, ORDER_AT) VALUES (5, 'ORD101', '2023-01-04 18:20:00');

CREATE TABLE `ORDER_ITEMS` (
    `ID` INT(11) PRIMARY KEY AUTO_INCREMENT,
    `ORDER_ID` INT(11) NOT NULL,
    `PRODUCT_ID` INT(11) NOT NULL,
    `PRICE` DECIMAL(10,2) NOT NULL,
    `QUANTITY` BIGINT NOT NULL 
);
ALTER TABLE `ORDER_ITEMS` ADD COLUMN (`PRICE` DECIMAL(10,2) NOT NULL);

ALTER TABLE `ORDER_ITEMS` ADD FOREIGN KEY(ORDER_ID) REFERENCES `ORDERS`(ID);

ALTER TABLE `ORDER_ITEMS` ADD FOREIGN KEY(PRODUCT_ID) REFERENCES `PRODUCTS`(ID);

DESC `ORDER_ITEMS`;

INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, PRICE, QUANTITY) VALUES (3, 1, 50000, 1);
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, PRICE, QUANTITY) VALUES (2, 3, 25000, 1);
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, PRICE, QUANTITY) VALUES (1, 2, 30000, 2);

#Retrieve all products
SELECT * FROM `PRODUCTS`;

#Retrieve all customers
SELECT * FROM `CUSTOMERS`;

#Retrieve all orders
SELECT * FROM `ORDERS`;

#Retrieve all order items
SELECT * FROM `ORDER_ITEMS`;

#Retrieve orders for a specific customer
SELECT * FROM Orders WHERE CUSTOMER_ID = 1;

#Calculate the total price of an order
SELECT SUM(PRICE * QUANTITY) AS TOTAL_PRICE FROM OrderItems WHERE ORDER_ID = 2;

#Retrieve address starting with vowels
SELECT DISTINCT ADDRESS
FROM CUSTOMERS
WHERE UPPER(LEFT(ADDRESS, 1)) IN ('A', 'E', 'I', 'O', 'U');
